apiVersion: v1
kind: Pod
metadata:
  name: mon-premier-pod
  namespace: jcanon
  labels:
    app: web
spec:
  containers:
  - name: mon-container-nginx
    image: nginx
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume
  - name: rss-reader
    image: nickchase/rss-php-nginx:v1
    ports:
      - containerPort: 88
  volumes:
  - name: cache-volume
    emptyDir: {}
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "echo Bonjour >/usr/share/nginx/html/index.html"]
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume

