---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    truc: un_truc
    label: des_champs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: nginx
        image: nginx:1.17