---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 
  labels:
    truc: un_truc
    label: rouge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: nginx:1.18
