apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
  labels:
    truc: labeldureplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webserver
        image: nginx:1.19

