apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    info: un_label_pour_webserver-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web

